### ISSUE TITLE
Side VRF resetting to blank

### ISSUE THREAD

**Issue by gpipito** [robertlynch3/netbox-tunnels2#8] opened 2023-06-14 08:35 UTC
**NetBox version**
3.5.1

**Describe the bug**
Side A/B Address VRF does not get updated. Also there is no way to show it in the table view.

**To Reproduce**
1. Edit tunnel item
2. Select a VRF from the Side A/B Address VRF dropdown menu 
3. Save

**Expected behavior**
The updated data should be persisted and shown in the table view.

**Screenshots**
1. I set the Side A Address VRF
![image](https://github.com/robertlynch3/netbox-tunnels2/assets/50398686/a55a8307-9cce-49cf-bbea-a86a6c670df3)

2. data is properly saved
![image](https://github.com/robertlynch3/netbox-tunnels2/assets/50398686/1e7201ff-57af-4007-b8cd-1e7493ad1850)

3. info is missing in tunnel details view
![image](https://github.com/robertlynch3/netbox-tunnels2/assets/50398686/3aa6001d-cea4-4311-a61b-29a6adc0baae)

4. fields are missing in table configuration
![image](https://github.com/robertlynch3/netbox-tunnels2/assets/50398686/6d5cc75a-87f8-482e-9bd1-018309cc4b55)

5. the field is reset to blank if I edit the tunnel again

**Comment by robertlynch3** [comment] 2023-06-14 13:27
This is not a bug. The VRF field is just a search field for the IP, it’s not actually stored in model. It may be possible to fill it based on what the IP’s information.

**Comment by gpipito** [comment] 2023-06-26 08:23
I got the point. However it would be a nice improvement to have a VRF relationship for each tunnel.

**Comment by robertlynch3** [comment] 2023-08-30 15:03
Fixed in #15.

**Closed as completed by robertlynch3** 2023-08-30 15:03 UTC
Labels: enhancement
